<a href="https://colab.research.google.com/github/DeepHiveMind/Models-used-in-Deep-Learning-and-Deep-Reinforcement-Learning/blob/master/Tensorflow_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
tf.square(4-2)

<tf.Tensor 'Square:0' shape=() dtype=int32>

In [0]:
import pandas as pd
import numpy as np
y=pd.DataFrame(["a","b","a","b","c","b","a","c","b","b","a","b"])

In [0]:
y

0
0  a
1  b
2  a
3  b
4  b
5  a
6  b
7  b
8  a
9  b

In [0]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
encoder.fit(y)
y=encoder.transform(y)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
y

array([0, 1, 0, 1, 2, 1, 0, 2, 1, 1, 0, 1])

In [0]:
def one_hot_encode(label):
  n_labels=len(label)
  n_unique_labels=len(np.unique(label))
  one_hot_encode= np.zeros((n_labels,n_unique_labels))
  print(one_hot_encode)
  a=np.arange(n_labels)
  b=label
  print(a)
  print(b)
  one_hot_encode[np.arange(n_labels),[1,2]]=5
  return one_hot_encode

In [0]:
Y=one_hot_encode(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 0 1 2 1 0 2 1 1 0 1]


IndexError: ignored

In [0]:
Y

array([[0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.]])

In [0]:
from __future__ import print_function

from keras.models import Model
from keras.layers import Input, LSTM, Dense
import numpy as np

batch_size = 64  # Batch size for training.
epochs = 100  # Number of epochs to train for.
latent_dim = 256  # Latent dimensionality of the encoding space.
num_samples = 10000  # Number of samples to train on.
# Path to the data txt file on disk.
data_path = 'F:/Misc/fra-eng/fra.txt'

In [0]:
data_path

'file:///F:/Misc/fra-eng/fra.txt'

In [0]:
# Vectorize the data.
input_texts = []
target_texts = []
input_characters = set()
target_characters = set()
with open(data_path, 'r', encoding='utf-8') as f:
    lines = f.read().split('\n')
for line in lines[: min(num_samples, len(lines) - 1)]:
    input_text, target_text = line.split('\t')
    # We use "tab" as the "start sequence" character
    # for the targets, and "\n" as "end sequence" character.
    target_text = '\t' + target_text + '\n'
    input_texts.append(input_text)
    target_texts.append(target_text)
    for char in input_text:
        if char not in input_characters:
            input_characters.add(char)
    for char in target_text:
        if char not in target_characters:
            target_characters.add(char)

FileNotFoundError: ignored